---
name: 🐞 Bug Report
description: |-
  Tell us about something that's not working the way you think it should.
  # Please read the troubleshooting section (fix me) first.

body:
  - type: markdown
    attributes:
      value: |-
        Please read the [troubleshooting section](https://github.com/mfussenegger/nvim-jdtls#troubleshooting) first.
        [Please make it easy for people to help you](https://zignar.net/2021/12/03/help-people-help-you-and-put-in-some-effort/)
  - type: textarea
    id: config
    attributes:
      label: Cookiecutter Configuration
      description: The configuration you pass to the plugin, if you did it
  - type: input
    id: version
    attributes:
      label: Cookiecutter version
      placeholder: 1.0.1
    validations:
      required: false
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we see what you're seeing? Please be specific
      placeholder: |-
        In a project using { gradle version .. | maven .. } (Ideally with link), opening a Java file ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: Output? Logs? Post the maven/gradle output if there is any.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## Thanks for reporting 🙏
