name: 💡 Feature or Enhancement Request
labels: ["feature", "enhancement", "new"]
assignees:
  - luiz-micci
  - peppetwer
description: Tell us about a problem you'd like to solve
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem could it solve that it doesn't?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Ideas or possible solutions
      description: Share your ideas about potential solutions
      placeholder: |-
        🤷
    validations:
      required: false
  - type: markdown
    attributes:
      value: |-
        ## Thanks for collaborate 🙏
