name: 🔧 General Issue
labels: ["issue", "new"]
assignees:
  - luiz-micci
  - peppetwer
description: Elaborate about your issue
body:
  - type: textarea
    attributes:
      label: Description
    id: desc
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## Thanks for collaborate 🙏
