name: Reusable Workflow Build For PRs

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-steps:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "11"
          cache: "maven"

      - name: Build with Maven
        run: mvn -X clean install -Dgpg.skip=true
        env:
          MAVEN_CONFIG: ""
