# .github/workflows/block-dotgithub.yml (this is what PRs trigger)
name: Safe Build PR

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  check-safe-pr-build:
    uses: thoughtworks/templify/.github/workflows/reusable/pr_build.yml@main
