name: Build PR

on:
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  run-steps:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "11"
          cache: "maven"
          server-username: ${{secrets.USERNAME}}
          server-password: ${{secrets.PASSWORD}}

      - name: Build with Maven
        run: mvn -X clean install -Dgpg.skip=true
