name: Pull request checks

on:
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  safe_pr_checks:
    uses: thoughtworks/templify/.github/workflows/safe_pr_checks.yml@main
