name: Reusable Workflow Build For PRs

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "11"

      - name: Verify Java version
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          which java
          java -version

      - name: Verify Maven version
        run: mvn -v

      - name: Build with Maven
        run: mvn clean package -Dgpg.skip=true
        env:
          MAVEN_CONFIG: ""
          
      - name: Verify Mutation Coverage
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          which java
          java -version
          mvn test-compile org.pitest:pitest-maven:mutationCoverage -Djava.home=$JAVA_HOME
        env:
          MAVEN_CONFIG: ""
